# Generated by Django 5.2.1 on 2025-05-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='richiesta_fattura',
            field=models.BooleanField(default=False),
        ),
    ]
