# Generated by Django 5.2.1 on 2025-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0002_alter_ordine_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Carta di credito', 'Carta Credito'), ('PayPal', 'Paypal'), ('Bonifico', 'Bonifico')], default='Carta di credito', max_length=50),
        ),
    ]
