# Generated by Django 5.2.1 on 2025-05-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0002_ordine_richiesta_fattura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='centro_distributivo',
        ),
        migrations.RemoveField(
            model_name='gestione',
            name='centro_distributivo',
        ),
        migrations.RemoveField(
            model_name='partecipazione_evento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='recensione',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dettaglio_ordine',
            name='ordine',
        ),
        migrations.RemoveField(
            model_name='dettaglio_ordine',
            name='prodotto',
        ),
        migrations.RemoveField(
            model_name='recensione',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='partecipazione_evento',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='gestione',
            name='ordine',
        ),
        migrations.RemoveField(
            model_name='recensione',
            name='prodotto',
        ),
        migrations.DeleteModel(
            name='Centro_Distributivo',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Dettaglio_ordine',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Partecipazione_evento',
        ),
        migrations.DeleteModel(
            name='Gestione',
        ),
        migrations.DeleteModel(
            name='Ordine',
        ),
        migrations.DeleteModel(
            name='Prodotto',
        ),
        migrations.DeleteModel(
            name='Recensione',
        ),
    ]
