# Generated by Django 5.2.1 on 2025-06-01 12:37

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0003_alter_ordine_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='metodo_pagamento',
            field=django_mysql.models.EnumField(choices=[('Carta di credito', 'Carta di credito'), ('PayPal', 'PayPal'), ('Bonifico', 'Bonifico')], default='Carta di credito'),
        ),
    ]
