# Generated by Django 5.2.1 on 2025-05-16 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tenuta', '0003_remove_ordine_centro_distributivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_Distributivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regione', models.CharField(choices=[('Veneto', 'Veneto'), ('Puglia', 'Puglia')], max_length=20)),
                ('indirizzo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('responsabile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('ruolo', models.CharField(choices=[('privato', 'Privato'), ('commerciale', 'Commerciale')], max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('ragione_sociale', models.CharField(max_length=100)),
                ('partita_iva', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=100)),
                ('data_evento', models.DateField()),
                ('descrizione', models.TextField()),
                ('luogo_evento', models.CharField(max_length=255)),
                ('iscrizione', models.BooleanField(default=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('immagine', models.ImageField(upload_to='prodotti/')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantita_disponibile', models.IntegerField()),
                ('formato', models.CharField(max_length=50)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], max_length=20)),
                ('data_ordine', models.DateField()),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('indirizzo_spedizione', models.CharField(max_length=255)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_consegna', models.CharField(choices=[('standard', 'Standard'), ('espresso', 'Espresso')], max_length=20)),
                ('richiesta_fattura', models.BooleanField(default=False)),
                ('centro_distributivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.centro_distributivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Gestione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_distributivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.centro_distributivo')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.ordine')),
            ],
        ),
        migrations.CreateModel(
            name='Partecipazione_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partecipanti', models.PositiveIntegerField()),
                ('stato', models.CharField(choices=[('confermato', 'Confermato'), ('annullato', 'Annullato'), ('attesa', 'Attesa')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Dettaglio_ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.prodotto')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testo', models.TextField()),
                ('valutazione', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.evento')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.prodotto')),
            ],
        ),
    ]
