# Generated by Django 5.2.1 on 2025-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_distributivo',
            name='regione',
            field=models.CharField(choices=[('Veneto', 'Veneto'), ('Puglia', 'Puglia')], default='Veneto', max_length=20),
        ),
    ]
