# Generated by Django 5.2.1 on 2025-06-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0004_alter_ordine_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tenuta.evento'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='prodotto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tenuta.prodotto'),
        ),
    ]
