# Generated by Django 5.2.1 on 2025-05-20 10:07

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0005_alter_centro_distributivo_regione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_distributivo',
            name='regione',
            field=django_mysql.models.EnumField(choices=[('Veneto', 'Veneto'), ('Puglia', 'Puglia')], default='Veneto'),
        ),
    ]
