# Generated by Django 5.2.1 on 2025-06-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0005_alter_recensione_evento_alter_recensione_prodotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='iscrizione',
            field=models.IntegerField(default=True),
        ),
    ]
