# Generated by Django 5.2.1 on 2025-06-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0006_alter_evento_iscrizione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='centro_distributivo',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='cliente',
        ),
    ]
