# Generated by Django 5.2.1 on 2025-05-20 20:16

import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0006_alter_centro_distributivo_regione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsabile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='centro_distributivo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='centro_distributivo',
            name='password',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruolo',
            field=django_mysql.models.EnumField(choices=[('Privato', 'Privato'), ('Commerciale', 'Commerciale')], default='Privato'),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=django_mysql.models.EnumField(choices=[('attesa', 'Attesa'), ('Spedito', 'Spedito'), ('Consegnato', 'Consegnato'), ('Annullato', 'Annullato')], default='attesa'),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='tipo_consegna',
            field=django_mysql.models.EnumField(choices=[('Standard', 'Standard'), ('Espresso', 'Espresso')], default='Standard'),
        ),
        migrations.AlterField(
            model_name='partecipazione_evento',
            name='stato',
            field=django_mysql.models.EnumField(choices=[('confermato', 'Confermato'), ('annullato', 'Annullato'), ('attesa', 'Attesa')], default='confermato'),
        ),
        migrations.AlterField(
            model_name='centro_distributivo',
            name='responsabile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.responsabile'),
        ),
    ]
