# Generated by Django 5.2.1 on 2025-05-20 20:18

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0007_responsabile_remove_centro_distributivo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=django_mysql.models.EnumField(choices=[('Attesa', 'Attesa'), ('Spedito', 'Spedito'), ('Consegnato', 'Consegnato'), ('Annullato', 'Annullato')], default='Attesa'),
        ),
    ]
