# Generated by Django 5.2.1 on 2025-05-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0008_alter_ordine_stato'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gestione',
            unique_together={('ordine', 'centro_distributivo')},
        ),
    ]
