# Generated by Django 5.2.1 on 2025-05-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenuta', '0009_alter_gestione_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esecuzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.cliente')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.ordine')),
            ],
        ),
        migrations.CreateModel(
            name='Registrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_distributivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.centro_distributivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenuta.cliente')),
            ],
        ),
    ]
